name: Human Aware Rllib

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build_osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Python setup #removed conda setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
          cache: "pip"
      - name: Installing dependencies
        run: pip install -r requirements.txt
      - name: Test with unittest
        run: |
          sudo chmod 777 ./run_tests.sh
          ./run_tests.sh
